name: Test CI

on: 
  push:
    branches: 
      - 'download-files-automatically'

# Don't use a cache here: 
#  This is the last instance that can detect missing dependecies

jobs:
  build_release:
    name: Build & Release
    #no integration tests so far
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup - .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      
      - name: Build - Dotnet Build Release
        run: dotnet build --configuration Release
        
        #Build and prepare build tool
      - name: Publish build tool - ADB
        working-directory: ADB
        run: dotnet publish -c Release
                      
      - name: Move build tool to build folder - ADB
        run: cp ADB/bin/Release/netcoreapp3.1/publish/* build
      
      - name: Self test build tool - ADB
        working-directory: build
        run: ./ADB --version
                  
        #Pack variants
        #TODO: a) should work parallel b) less redundant code
        #Variant: Win64
      - name: Publish win-x64 - Dotnet Publish Release
        working-directory: Aves
        run: dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true
                
      - name: Download dependencies of win-x64 - ADB
        working-directory: build
        run: ./ADB -c config.json --rid win-x64 --bc Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        #Ignore pdb files
      - name: Pack win-x64 - Zip
        working-directory: Aves/bin/Release/netcoreapp3.1/win-x64/publish/
        run: zip -r Aves.zip . -x \*.pdb
        
          
